eureka:
  instance:
    non-secure-port: ${server.port:8087}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://59.110.221.220:8761/eureka/
ribbon:
  eager-load:
    enabled: true
    clients: ai-reading-user-prod
  ConnectTimeout: 5000
  ReadTimeout: 15000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
