eureka:
  instance:
    non-secure-port: ${server.port:8087}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 15000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
